name: Toggle Maintenance Mode

on:
  workflow_dispatch:
    inputs:
      maintenance_mode:
        description: Enable maintenance mode
        required: true
        type: boolean
        default: false

jobs:
  toggle-maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update Environment Variable
        run: echo "NEXT_PUBLIC_MAINTENANCE_MODE=${{ github.event.inputs.maintenance_mode }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel env add NEXT_PUBLIC_MAINTENANCE_MODE production ${{ github.event.inputs.maintenance_mode }} --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes
          npx vercel deploy --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes 